services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastfood-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

#  backend:
#    env_file:
#      - .env
#    build:
#      context: src
#      dockerfile: Dockerfile
#    container_name: auth-fastfood-backend
#    ports:
#      - "8083:8083"
#    environment:
#      POSTGRES_DOCKER: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}
#    networks:
#      - fastfood-network
#    depends_on:
#      postgres:
#        condition: service_healthy

volumes:
  postgres_data:

networks:
  fastfood-network: